# These are supported funding model platforms for KitMedia

github: # [kitmedia-team] # Replace with your GitHub username when ready
patreon: # kitmedia # Replace with your Patreon username when ready
open_collective: # kitmedia # Replace with your Open Collective username when ready
ko_fi: # kitmedia # Replace with your Ko-fi username when ready
custom: # ['https://www.buymeacoffee.com/kitmedia'] # Replace with your custom donation links when ready

# Uncomment and fill in the platforms you want to use for funding
# Remove the # symbol and add your actual usernames/links